name: Elixir CI

on: [push, pull_request]



jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.14.x # Define the elixir version [required]
        otp-version: 25.x # Define the OTP version [required]
        experimental-otp: true
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test